spring:
  datasource:
    url: jdbc:mysql://132.232.137.150:3306/liwei?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: xiaowei
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8888
